{
 "title": "StarRocks Overview（细粒度内存监控）",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(up, job)" } },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_name\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_name\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", job=\"$cluster_name\"}"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Number",
     "type": "stat",
     "description": "Num of  StarRocks Clusters",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(node_info{type=\"is_master\"})"
      }
     ]
    },
    {
     "title": "Frontends Status",
     "type": "graph",
     "description": "Dead Frontends will be shown as Colored points.\nIf all Frontends are alive, all points should be Green.",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(up{group=\"fe\"} == 0) +0",
       "legendFormat": "{{job}}-{{instance}}: DEAD"
      },
      {
       "expr": "(up{group=\"fe\"} == 1) +0",
       "legendFormat": "{{job}}-{{instance}}: ALIVE"
      }
     ]
    },
    {
     "title": "Backends status",
     "type": "graph",
     "description": "Dead Backends will be shown as Colored points.\nIf all Backends are alive, all points should be Green.",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(up{group=\"be\"} == 0) +0",
       "legendFormat": "{{job}}-{{instance}}: DEAD"
      },
      {
       "expr": "(up{group=\"be\"} == 1) +0",
       "legendFormat": "{{job}}-{{instance}}: ALIVE"
      }
     ]
    },
    {
     "title": "Cluster FE JVM Heap Stat",
     "type": "graph",
     "description": "The JVM heap usage percent of each Frontend of each StarRocks cluster.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_heap_size_bytes{group=\"fe\", type=\"used\"} * 100) by (instance, job) / sum(jvm_heap_size_bytes{group=\"fe\", type=\"max\"}) by (instance, job)",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster BE CPU Idle",
     "type": "graph",
     "description": "The Backend CPU idle overview of each StarRocks cluster.\nThe detail Backend CPU idle info can be seen in 'BE' section.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(starrocks_be_cpu{mode=\"idle\"}[$interval])) by (job)) / (sum(rate(starrocks_be_cpu[$interval])) by (job))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster BE Mem Stat",
     "type": "graph",
     "description": "The Backend memory usage overview of each StarRocks cluster.\nThe detail backend memory usage can be seen in 'BE' section.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(starrocks_be_process_mem_bytes) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster QPS Stat",
     "type": "graph",
     "description": "QPS statistic group by cluster.\nThe QPS of each cluster is the sum of all queries processed on all Frontends.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(rate(starrocks_fe_query_total{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster RPS Stat",
     "type": "graph",
     "description": "RPS statistic group by cluster.\nThe RPS of each cluster is the sum of all requests processed on all Frontends.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(rate(starrocks_fe_request_total{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cluster TPS Stat",
     "type": "graph",
     "description": "TPS statistic group by cluster.\nThe TPS of each cluster is the sum of all transaction processed on all Frontends.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(rate(starrocks_fe_txn_begin{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}-begin"
      },
      {
       "expr": "sum by (job)(rate(starrocks_fe_txn_success{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}-success"
      },
      {
       "expr": "sum by (job)(rate(starrocks_fe_txn_failed{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}-failed"
      },
      {
       "expr": "sum by (job)(rate(starrocks_fe_txn_reject{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}-reject"
      }
     ]
    },
    {
     "title": "Cluster Query Error",
     "type": "graph",
     "description": "Query Error statistic group by cluster.\nThe Query Error of each cluster is the sum of all failed queries processed on all Frontends.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(rate(starrocks_fe_query_err{group=\"fe\"}[$interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Disk State",
     "type": "graph",
     "description": "The Disk state. GREEN point means this disk is ONLINE. RED point means this disk is OFFLINE",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(starrocks_be_disks_state{job=\"$cluster_name\"} == 0)+0",
       "legendFormat": "{{instance}}: {{path}} OFFLINE"
      },
      {
       "expr": "(starrocks_be_disks_state{job=\"$cluster_name\"} == 1)+0",
       "legendFormat": "{{instance}}: {{path}} ONLINE"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "cluster_name",
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] FE Node",
     "type": "stat",
     "description": "Total Frontends node number",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{group=\"fe\", job=\"$cluster_name\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name] FE Node",
     "type": "stat",
     "description": "Total Frontends node number",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{group=\"fe\", job=\"$cluster_name\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Node",
     "type": "stat",
     "description": "Total Backends node number",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{group=\"be\", job=\"$cluster_name\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Alive",
     "type": "stat",
     "description": "Total alive number of Backends. Normally, it should be equal to the Total number of Backends.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(up{group=\"be\", job=\"$cluster_name\"}==1)"
      }
     ]
    },
    {
     "title": "[$cluster_name] Used Capacity",
     "type": "stat",
     "description": "Total used disk capacity of all Backends.",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(starrocks_be_disks_data_used_capacity{job=\"$cluster_name\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name] Total Capacity",
     "type": "stat",
     "description": "Total disk capacity of all Backends",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(starrocks_be_disks_total_capacity{job=\"$cluster_name\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name]  DataBase Count",
     "type": "stat",
     "description": "Total database number of Cluster. ",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "starrocks_fe_database_num{group=\"fe\", job=\"$cluster_name\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name]  Table Count",
     "type": "stat",
     "description": "Total table number of Cluster. ",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(starrocks_fe_table_num{job=\"$cluster_name\", instance=\"$fe_master\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name]  Tablet Count",
     "type": "stat",
     "description": "Total tablet number of Cluster. ",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(starrocks_fe_tablet_num{job=\"$cluster_name\", instance=\"$fe_master\"})"
      }
     ]
    },
    {
     "title": "[$cluster_name] BDBJE Write",
     "type": "graph",
     "description": "The left Y axes shows write latency of 99th. The right Y axes shows the write per seconds of journal.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_editlog_write_latency_ms{job=\"$cluster_name\", instance=\"$fe_master\",quantile=\"0.99\"}",
       "legendFormat": "{{instance}}-99th"
      },
      {
       "expr": "rate(starrocks_fe_edit_log_write{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "{{instance}}-rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Scheduling Tablets",
     "type": "graph",
     "description": "Number of tablets begin scheduled. These tablet may be in recovery process or balance process",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_scheduled_tablet_num{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "Scheduling tablet number"
      }
     ]
    },
    {
     "title": "[$cluster_name] Max Replayed journal id",
     "type": "graph",
     "description": "The max replayed meta data journal id on Frontends.\nNormally, all Frontends should be same on this metrics, or just slightly different for a short period.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_max_journal_id{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Max Compaction Score",
     "type": "graph",
     "description": "The compaction score of each backend.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_tablet_max_compaction_score{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] FE Metalog Count",
     "type": "graph",
     "description": "The metalog count of each FE",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_meta_log_count{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE IO Util",
     "type": "graph",
     "description": "The max IO util of each Backend",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_max_disk_io_util_percent{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] RPS",
     "type": "graph",
     "description": "Requests per seconds on each Frontends.\nRequests include all requests sending to the Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_fe_request_total{job=\"$cluster_name\", group=\"fe\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] QPS",
     "type": "graph",
     "description": "Queries per seconds on each Frontends.\nQueries only include Select requests.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_fe_query_total{job=\"$cluster_name\", group=\"fe\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] 99th Latency",
     "type": "graph",
     "description": "99 quantiles of query latency on each Frontends.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(starrocks_fe_query_latency_ms{job=\"$cluster_name\", quantile=\"0.99\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] Query Percentile",
     "type": "graph",
     "description": "Left Y axes indicates 95 to 99 quantiles of query latency on each Frontends.\nRight Y axes indicates the query rate per 1 min.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_query_latency_ms{job=\"$cluster_name\", instance=\"$fe_instance\"}",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "rate(starrocks_fe_query_latency_ms_count{job=\"$cluster_name\", instance=\"$fe_instance\"}[1m])",
       "legendFormat": "query rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Query Error [1m]",
     "type": "graph",
     "description": "Left Y axes indicates the accumulated  error queries number.\nRight Y axes indicates the error query rate per 1 min.\nNormally, the error query rate should be 0.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_query_err{job=\"$cluster_name\"}",
       "legendFormat": "Err Counter-{{instance}}"
      },
      {
       "expr": "rate(starrocks_fe_query_err{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "Err Rate-{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Connections",
     "type": "graph",
     "description": "The connections' number to each Frontends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_connection_total{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Group CPU",
     "type": "graph",
     "description": "CPU used by resource group.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_cpu_use_ratio{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      },
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_cpu_limit_ratio{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      }
     ]
    },
    {
     "title": "Resource Group Mem",
     "type": "graph",
     "description": "Memory used by resource group.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_mem_inuse_bytes{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      },
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_mem_limit_bytes{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      }
     ]
    },
    {
     "title": "Queries",
     "type": "graph",
     "description": "Number of queries in the resource group.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_fe_query_resource_group{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      }
     ]
    },
    {
     "title": "Failed Queries",
     "type": "graph",
     "description": "Number of queries reporting errors in the resource group.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_fe_query_resource_group_err{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name }}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "description": "Latency of queries in the resource group",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_fe_query_resource_group_latency{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name }}"
      }
     ]
    },
    {
     "title": "Scan Used Ratio",
     "type": "graph",
     "description": "Instantaneous value of resource group CPU quota ratio",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_scan_use_ratio{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name}}"
      }
     ]
    },
    {
     "title": "Concurrency Overflow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_concurrency_overflow_count{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name }}"
      }
     ]
    },
    {
     "title": "Connector Used Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_connector_scan_use_ratio{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name }}"
      }
     ]
    },
    {
     "title": "Big Query Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,name)(starrocks_be_resource_group_bigquery_count{job=\"$cluster_name\"})",
       "legendFormat": "{{ instance }}-{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] Load submit",
     "type": "graph",
     "description": "Show the counter of Load job submitted and Load job finished.\nThe two lines show be paralleled if the load submit is a routine operations.\nRight Y axes shows the submit rate of load job",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_load_add{instance=\"$fe_master\"}",
       "legendFormat": "{{instance}}-Submit"
      },
      {
       "expr": "starrocks_fe_load_finished{instance=\"$fe_master\"}",
       "legendFormat": "{{instance}}-Finished"
      },
      {
       "expr": "rate(starrocks_fe_load_add{instance=\"$fe_master\"}[1h])",
       "legendFormat": "{{instance}}-Submit rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Report queue size",
     "type": "graph",
     "description": "Queue size of report in Master FE.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_report_queue_size{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "Report queue size"
      }
     ]
    },
    {
     "title": "[$cluster_name] Broker Load Job",
     "type": "table-old",
     "description": "Statistic of Broker load jobs's num in each Load State.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Broker load tendency",
     "type": "graph",
     "description": "The trend report of broker load job",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      }
     ]
    },
    {
     "title": "[$cluster_name] Stream Load Job",
     "type": "table-old",
     "description": "Statistic of load jobs's num  in each Load State which is generated by Stream Load Stmt.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "starrocks_fe_job{exported_job=\"load\",job=\"$cluster_name\",type=\"STREAM_LOAD\",instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Stream load tendency",
     "type": "graph",
     "description": "The trend report of stream load job",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"STREAM_LOAD\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"STREAM_LOAD\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"STREAM_LOAD\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"STREAM_LOAD\", instance=\"$fe_master\", state=\"CANCELLED\"}",
       "legendFormat": "CANCELLED"
      }
     ]
    },
    {
     "title": "[$cluster_name] Insert Load Job",
     "type": "table-old",
     "description": "Statistic of load jobs's num  in each Load State which is generated by Insert Stmt.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Insert load tendency",
     "type": "graph",
     "description": "The trend report of insert load job",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"PENDING\"}",
       "legendFormat": "PENDING"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"ETL\"}",
       "legendFormat": "ETL"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"LOADING\"}",
       "legendFormat": "LOADING"
      },
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"CANCELLED\"}",
       "legendFormat": "CANCELLED"
      }
     ]
    },
    {
     "title": "[$cluster_name] Routine Load Job",
     "type": "table-old",
     "description": "Statistic of load jobs's num  in each Load State which is generated by Routine Stmt.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "starrocks_fe_routine_load_jobs{job=\"$cluster_name\",instance=\"$fe_master\"}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Routine load tendency",
     "type": "graph",
     "description": "The trend report of routine load job",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_routine_load_jobs{job=\"$cluster_name\",instance=\"$fe_master\", state=\"CANCELLED\"}",
       "legendFormat": "NEED_SCHEDULE"
      },
      {
       "expr": "starrocks_fe_routine_load_jobs{job=\"$cluster_name\",instance=\"$fe_master\", state=\"PAUSED\"}",
       "legendFormat": "PAUSED"
      },
      {
       "expr": "starrocks_fe_routine_load_jobs{job=\"$cluster_name\",instance=\"$fe_master\", state=\"CANCELLED\"}",
       "legendFormat": "CANCELLED"
      }
     ]
    },
    {
     "title": "[$cluster_name] Schema Change Job",
     "type": "table-old",
     "description": "Number of running schema change jobs.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "starrocks_fe_job{job=\"$cluster_name\", instance=\"$fe_master\", type=\"SCHEMA_CHANGE\"}",
       "legendFormat": "asds"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] Txn Begin/Success on FE",
     "type": "graph",
     "description": "Show the number and rate of txn begin and success",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_txn_begin{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "txn begin"
      },
      {
       "expr": "starrocks_fe_txn_success{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "txn success"
      },
      {
       "expr": "irate(starrocks_fe_txn_begin{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn begin rate"
      },
      {
       "expr": "irate(starrocks_fe_txn_success{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn success rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Failed/Reject on FE",
     "type": "graph",
     "description": "Show the failed txn request. Including rejected request and failed txn",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_fe_txn_reject{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn reject rate"
      },
      {
       "expr": "rate(starrocks_fe_txn_failed{job=\"$cluster_name\", instance=\"$fe_master\"}[$interval])",
       "legendFormat": "txn failed rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] Publish Task on BE",
     "type": "graph",
     "description": "The number of total publish task request and error rate.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"publish\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"publish\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Requset on BE",
     "type": "graph",
     "description": "Show the txn request on BE",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(starrocks_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"begin\"})",
       "legendFormat": "begin"
      },
      {
       "expr": "sum(starrocks_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"exec\"})",
       "legendFormat": "exec"
      },
      {
       "expr": "sum(starrocks_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"commit\"})",
       "legendFormat": "commit"
      },
      {
       "expr": "sum(starrocks_be_txn_request{group=\"be\", job=\"$cluster_name\", type=\"rollback\"})",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "[$cluster_name] Txn Load Bytes/Rows rate",
     "type": "graph",
     "description": "Left Y axes indicates the total received bytes rate of txn. Right Y axes indicates the loaded rows rate of txn.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(starrocks_be_stream_load{group=\"be\", job=\"$cluster_name\", type=\"receive_bytes\"}[$interval]))",
       "legendFormat": "bytes"
      },
      {
       "expr": "sum(rate(starrocks_be_stream_load{group=\"be\", job=\"$cluster_name\", type=\"load_rows\"}[$interval]))",
       "legendFormat": "rows"
      }
     ]
    }
   ]
  },
  {
   "title": "FE JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] [$fe_instance] JVM Heap",
     "type": "graph",
     "description": "JVM Heap usage of specified Frontend.\nLeft Y Axes shows the used/max heap size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}) * 100 / sum(jvm_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Non Heap",
     "type": "graph",
     "description": "JVM Non Heap usage of specified Frontend.\nLeft Y Axes shows the used/committed non heap size.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_non_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_non_heap_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"committed\"}",
       "legendFormat": "committed"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Direct Buffer",
     "type": "graph",
     "description": "JVM Direct buffer usage of specified Frontend.\nLeft Y Axes shows the used/capacity direct buffer size.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_direct_buffer_pool_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_direct_buffer_pool_size_bytes{instance=\"$fe_instance\", job=\"$cluster_name\", type=\"capacity\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "[$cluster_name] JVM Threads",
     "type": "graph",
     "description": "Num of threads of FE JVM",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_thread{job=\"$cluster_name\", group=\"fe\", type=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Young",
     "type": "graph",
     "description": "JVM young generation usage of specified Frontend.\nLeft Y Axes shows the used/max young generation size.\nRight Y Axes shows the used percentage.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_young_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Old",
     "type": "graph",
     "description": "JVM old generation usage of specified Frontend. Left Y Axes shows the used/max old generation size. Right Y Axes shows the used percentage.\nNormally, the usage percentage should be less than 80%.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"}",
       "legendFormat": "max"
      },
      {
       "expr": "sum(jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_old_size_bytes{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"max\"})",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Young GC",
     "type": "graph",
     "description": "JVM young gc stat of specified Frontend. \nLeft Y Axes shows times of young gc.\nRight Y Axes shows the time cost of each young gc.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"}",
       "legendFormat": "count"
      },
      {
       "expr": "sum(jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"time\"}) / sum(jvm_young_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"})",
       "legendFormat": "avg time"
      }
     ]
    },
    {
     "title": "[$cluster_name] [$fe_instance] JVM Old GC",
     "type": "graph",
     "description": "JVM full gc stat of specified Frontend. \nLeft Y Axes shows times of full gc.\nRight Y Axes shows the time cost of each full gc.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"}",
       "legendFormat": "count"
      },
      {
       "expr": "sum(jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"time\"}) / sum(jvm_old_gc{job=\"$cluster_name\", instance=\"$fe_instance\", type=\"count\"})",
       "legendFormat": "avg time"
      }
     ]
    }
   ]
  },
  {
   "title": "BE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] BE CPU Idle",
     "type": "graph",
     "description": "CPU idle stat of Backends.\nLow means CPU is busy.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(starrocks_be_cpu{mode=\"idle\", job=\"$cluster_name\"}[$interval])) by (job, instance)) / (sum(rate(starrocks_be_cpu{job=\"$cluster_name\"}[$interval])) by (job, instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Mem",
     "type": "graph",
     "description": "Memory usage of Backends.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_jemalloc_allocated_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Net send/receive bytes",
     "type": "graph",
     "description": "Network send(Left Y)/receive(Right Y) bytes rate of all device except 'lo'",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(starrocks_be_network_send_bytes{job=\"$cluster_name\", group=\"be\", device!=\"lo\"}[$interval])",
       "legendFormat": "{{instance}}-{{device}}-send"
      },
      {
       "expr": "irate(starrocks_be_network_receive_bytes{job=\"$cluster_name\", group=\"be\", device!=\"lo\"}[$interval])",
       "legendFormat": "{{instance}}-{{device}}-receive"
      }
     ]
    },
    {
     "title": "[$cluster_name] Disk Usage",
     "type": "graph",
     "description": "Disk capacity usage of Backends",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(SUM(starrocks_be_disks_total_capacity{job=\"$cluster_name\"}) by (instance, path) - SUM(starrocks_be_disks_avail_capacity{job=\"$cluster_name\"}) by (instance, path)) / SUM(starrocks_be_disks_total_capacity{job=\"$cluster_name\"}) by (instance, path)",
       "legendFormat": "{{instance}}:{{path}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Disk IO util",
     "type": "graph",
     "description": "IO util of Backends.\nHigh means I/O is busy.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_disk_io_time_ms{job=\"$cluster_name\"}[$interval]) / 10",
       "legendFormat": "{{instance}}-{{device}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE FD count",
     "type": "graph",
     "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_process_fd_num_used{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}-used"
      },
      {
       "expr": "starrocks_be_process_fd_num_limit_soft{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}-soft limit"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE thread num",
     "type": "graph",
     "description": "The thread number of Backends",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_process_thread_num{job=\"$cluster_name\", group=\"be\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Tablet Distribution",
     "type": "graph",
     "description": "Number of tablets of each Backends",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "starrocks_fe_tablet_num{job=\"$cluster_name\", instance=\"$fe_master\"}",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Compaction Base",
     "type": "graph",
     "description": "Base compaction rate of Backends.\nNormally, base compaction only runs between 20:00 to 4:00 and it is configurable.\nRight Y axes indicates the total base compaction bytes.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_compaction_bytes_total{type=\"base\", job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(starrocks_be_compaction_bytes_total{type=\"base\", job=\"$cluster_name\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Compaction Cumulate",
     "type": "graph",
     "description": "Cumulative compaction rate of Backends.\nRight Y axes indicates the total cumulative compaction bytes.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_compaction_bytes_total{type=\"cumulative\", job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "SUM(starrocks_be_compaction_bytes_total{type=\"cumulative\", job=\"$cluster_name\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Push Bytes",
     "type": "graph",
     "description": "Loading rate of Backends.\nThis indicates the rate of file downloading in LOADING state of load job(MINI and BROKER load).\nRight Y axes indicates the total rate of file downloading.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_push_request_write_bytes{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(starrocks_be_push_request_write_bytes{job=\"$cluster_name\"}[$interval]))",
       "legendFormat": "Total rate"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Push Rows",
     "type": "graph",
     "description": "Loading rows rate of Backends.\nThis indicates the rate of rows loaded in LOADING state of load job. Right Y axes shows the total push rate of cluster.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_push_request_write_rows{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(starrocks_be_push_request_write_rows{job=\"$cluster_name\"}[$interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Scan Bytes",
     "type": "graph",
     "description": "Scan rate of Backends.\nThis indicates the read rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_query_scan_bytes{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "[$cluster_name] BE Scan Rows",
     "type": "graph",
     "description": "Scan rows rate of Backends.\nThis indicates the read rows rate when processing queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_query_scan_rows{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] BE Load Bytes",
     "type": "graph",
     "description": "Load rate of Backends.\nThis indicates the load rate.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_load_bytes{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "[$cluster_name] BE Load Rows",
     "type": "graph",
     "description": "Load rows rate of Backends.\nThis indicates the load rows rate.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(starrocks_be_load_rows{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      },
      {}
     ]
    },
    {
     "title": "[$cluster_name] Tablet Meta Write",
     "type": "graph",
     "description": "Left Y axes shows the write rate of tablet header saved in rocksdb. Right Y axes shows the duration of each write operation.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "irate(starrocks_be_meta_request_total{job=\"$cluster_name\", type=\"write\"}[$interval])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "starrocks_be_meta_request_duration{job=\"$cluster_name\", type=\"write\"} / starrocks_be_meta_request_total{job=\"$cluster_name\", type=\"write\"}",
       "legendFormat": "{{instance}}-latency"
      }
     ]
    },
    {
     "title": "[$cluster_name] Tablet Meta Read",
     "type": "graph",
     "description": "Left Y axes shows the read rate of tablet header saved in rocksdb. Right Y axes shows the duration of each read operation.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "irate(starrocks_be_meta_request_total{job=\"$cluster_name\", type=\"read\"}[$interval])",
       "legendFormat": "{{instance}}-rate"
      },
      {
       "expr": "starrocks_be_meta_request_duration{job=\"$cluster_name\", type=\"read\"} / starrocks_be_meta_request_total{job=\"$cluster_name\", type=\"read\"}",
       "legendFormat": "{{instance}}-latency"
      }
     ]
    }
   ]
  },
  {
   "title": "BE Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jemalloc Allocated Mem",
     "type": "graph",
     "description": "Memory counted by jemalloc.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_jemalloc_allocated_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Process Mem",
     "type": "graph",
     "description": "Memory counted by starrocks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_process_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Querying Mem",
     "type": "graph",
     "description": "Memory used by queries.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_query_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Loading Mem",
     "type": "graph",
     "description": "Memory used by Loading.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_load_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Updating Mem",
     "type": "graph",
     "description": "Memory used by updating.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_update_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Pagecache Mem",
     "type": "graph",
     "description": "Memory used by page cache.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_storage_page_cache_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Compaction Mem",
     "type": "graph",
     "description": "Memory used by compaction.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_compaction_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Consistency Mem",
     "type": "graph",
     "description": "Memory used by calculating checksum.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_consistency_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Replica Cloning Mem",
     "type": "graph",
     "description": "Memory used by replica cloning.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_clone_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Schema changing Mem ",
     "type": "graph",
     "description": "Memory used by schema changing.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_schema_change_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Chunk Allocator Mem",
     "type": "graph",
     "description": "Memory used by chunk cllocator.Cache for improved memory allocation performance",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_chunk_allocator_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "BE Metadata Mem",
     "type": "graph",
     "description": "Memory used by backennd meta.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_metadata_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Bitmap Index Mem",
     "type": "graph",
     "description": "Memory used by bitmap index.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_bitmap_index_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "BloomFilter Index Mem",
     "type": "graph",
     "description": "Memory used by bloomfilter index.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_bloom_filter_index_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Ordinal Index Mem",
     "type": "graph",
     "description": "Memory used by ordinal index.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_ordinal_index_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Shortkey Index Mem",
     "type": "graph",
     "description": "Memory used by shortkey index.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_short_key_index_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Column Metadata Mem",
     "type": "graph",
     "description": "Memory used by column meta.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_column_metadata_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Column Zonemap Index Mem",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_column_zonemap_index_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Column Pool Mem",
     "type": "graph",
     "description": "Memory used by accel erating memory allocation.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_column_pool_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Segment Metadata Mem",
     "type": "graph",
     "description": "Memory used by segment meta.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_segment_metadata_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Rowset Metadata Mem",
     "type": "graph",
     "description": "Memory used by rowset meta.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_rowset_metadata_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Tablet Metadata Mem",
     "type": "graph",
     "description": "Memory used by tablet meta.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_tablet_metadata_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Tablet Schema Mem",
     "type": "graph",
     "description": "Memory used by tablet schema changing.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_tablet_schema_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    },
    {
     "title": "Segment Zonemap Mem",
     "type": "graph",
     "description": "Memory used by segment zonemap.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "starrocks_be_segment_zonemap_mem_bytes{job=\"$cluster_name\"}",
       "legendFormat": "{{ instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BE tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$cluster_name] Tablets Report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"report_all_tablets\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"report_all_tablets\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Single Tablet Report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"report_tablet\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"report_tablet\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Finish task report",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"finish_task\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"finish_task\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Push Task",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(starrocks_be_push_requests_total{job=\"$cluster_name\", status=\"SUCCESS\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_push_requests_total{job=\"$cluster_name\", status=\"FAIL\"}[$interval])",
       "legendFormat": "{{instance}}-failed"
      }
     ]
    },
    {
     "title": "[$cluster_name] Push Task Cost Time",
     "type": "graph",
     "description": "The average cost time of push tasks on each Backend.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(starrocks_be_push_request_duration_us{job=\"$cluster_name\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Delete",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"delete\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"delete\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Base Compaction",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"base_compaction\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"base_compaction\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Cumulative Compaction",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"cumulative_compaction\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"cumulative_compaction\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Clone",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"clone\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"clone\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Create rollup",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"create_rollup\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"create_rollup\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Schema change",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"schema_change\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"schema_change\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$cluster_name] Create tablet",
     "type": "graph",
     "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SUM(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"create_tablet\", status=\"total\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "irate(starrocks_be_engine_requests_total{job=\"$cluster_name\", type=\"create_tablet\", status=\"failed\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}